//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestAppPir.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestAppPir.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///    {
        ///        &quot;label&quot;: &quot;-&quot;,
        ///        &quot;id&quot;: &quot;139bc335-e53b-495d-9616-98a5f198860b&quot;
        ///    },    
        ///    {
        ///        &quot;label&quot;: &quot;Медрота, Красный октябрь&quot;,
        ///        &quot;id&quot;: &quot;869e9b04-299a-441b-9a07-cc92bbcd9909&quot;
        ///    },
        ///    {
        ///        &quot;label&quot;: &quot;ВГ Белгород&quot;,
        ///        &quot;id&quot;: &quot;2974bc60-2aef-40bf-8a6a-dd362ba42ece&quot;
        ///    },
        ///    {
        ///        &quot;label&quot;: &quot;ОГБУЗ Шебекинская ЦРБ &quot;,
        ///        &quot;id&quot;: &quot;59325076-2f65-486f-b656-e8fc4dc2f2e8&quot;
        ///    },
        ///    {
        ///        &quot;label&quot;: &quot;Филиал ФКУ «ЦВКГ им. П.В. Мандрыка» МО РФ клиника (преморб [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InstitutionsLocation {
            get {
                return ResourceManager.GetString("InstitutionsLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///    {
        ///        &quot;grp&quot;: &quot;-&quot;,
        ///        &quot;label&quot;: &quot;-&quot;,
        ///        &quot;id&quot;: &quot;9e8429eb-9b03-463f-877c-09d8776b816d&quot;
        ///    },
        ///    {
        ///        &quot;grp&quot;: &quot;Солдаты, матросы, сержанты, старшины&quot;,
        ///        &quot;label&quot;: &quot;Рядовой&quot;,
        ///        &quot;id&quot;: &quot;7e8244d4-1c7c-4c05-bea0-8eaeffc54294&quot;
        ///    },
        ///    {
        ///        &quot;grp&quot;: &quot;Солдаты, матросы, сержанты, старшины&quot;,
        ///        &quot;label&quot;: &quot;Матрос&quot;,
        ///        &quot;id&quot;: &quot;d2354cd1-20e1-4d75-80d2-54a00f0f296d&quot;
        ///    },
        ///    {
        ///        &quot;grp&quot;: &quot;Солдаты, матросы, сержанты, старшины&quot;,
        ///        &quot;label&quot;: &quot;Ефрейтор [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MilitaryRank {
            get {
                return ResourceManager.GetString("MilitaryRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///    {
        ///        &quot;label&quot;: &quot;-&quot;,
        ///        &quot;id&quot;: &quot;bf8fd633-d745-42a5-a524-76bb8afaec63&quot;
        ///    },
        ///    {
        ///        &quot;label&quot;: &quot;01069&quot;,
        ///        &quot;id&quot;: &quot;5bab98b0-3588-47dc-8b70-e0e9e3ed79ca&quot;
        ///    }
        ///].
        /// </summary>
        internal static string MilitaryUnit {
            get {
                return ResourceManager.GetString("MilitaryUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///    {
        ///        &quot;grp&quot;: &quot;-&quot;,
        ///        &quot;label&quot;: &quot;-&quot;,
        ///        &quot;id&quot;: &quot;ebac83b1-bdab-4d8f-aca2-42810002c520&quot;
        ///    },
        ///    {
        ///        &quot;grp&quot;: &quot;Акушерство и гинекология&quot;,
        ///        &quot;label&quot;: &quot;Акушер-гинеколог&quot;,
        ///        &quot;id&quot;: &quot;7aa012df-acab-414b-846f-05350d116e56&quot;
        ///    },
        ///    {
        ///        &quot;grp&quot;: &quot;Акушерство и гинекология&quot;,
        ///        &quot;label&quot;: &quot;Гинеколог&quot;,
        ///        &quot;id&quot;: &quot;8edf71c2-c99b-42ed-bd75-1ee1290673d2&quot;
        ///    },
        ///    {
        ///        &quot;grp&quot;: &quot;Акушерство и гинекология&quot;,
        ///        &quot;label&quot;: &quot;Хирург-гинеколог&quot;,
        ///        &quot;id&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Specialist {
            get {
                return ResourceManager.GetString("Specialist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///    {
        ///        &quot;label&quot;: &quot;-&quot;,
        ///        &quot;id&quot;: &quot;ffe83160-acce-434e-a04a-8cb9a37aca6c&quot;
        ///    },
        ///    {
        ///        &quot;label&quot;: &quot;Консультация&quot;,
        ///        &quot;id&quot;: &quot;a4808c06-ca79-4ae0-bc41-2a2eab25e3e9&quot;
        ///    },
        ///    {
        ///        &quot;label&quot;: &quot;Госпитализация&quot;,
        ///        &quot;id&quot;: &quot;1548f2c3-dc75-4d0d-a427-e62d2c4e7328&quot;
        ///    },
        ///    {
        ///        &quot;label&quot;: &quot;ВВК&quot;,
        ///        &quot;id&quot;: &quot;1de3524c-c537-49e3-8d6c-2f202b0321da&quot;
        ///    }
        ///].
        /// </summary>
        internal static string TypeOfDirection {
            get {
                return ResourceManager.GetString("TypeOfDirection", resourceCulture);
            }
        }
    }
}
