//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestAppPir.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestAppPir.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [
        ///    {
        ///        &quot;label&quot;: &quot;-&quot;,
        ///        &quot;id&quot;: &quot;139bc335-e53b-495d-9616-98a5f198860b&quot;
        ///    },    
        ///    {
        ///        &quot;label&quot;: &quot;Медрота, Красный октябрь&quot;,
        ///        &quot;id&quot;: &quot;869e9b04-299a-441b-9a07-cc92bbcd9909&quot;
        ///    },
        ///    {
        ///        &quot;label&quot;: &quot;ВГ Белгород&quot;,
        ///        &quot;id&quot;: &quot;2974bc60-2aef-40bf-8a6a-dd362ba42ece&quot;
        ///    },
        ///    {
        ///        &quot;label&quot;: &quot;ОГБУЗ Шебекинская ЦРБ &quot;,
        ///        &quot;id&quot;: &quot;59325076-2f65-486f-b656-e8fc4dc2f2e8&quot;
        ///    },
        ///    {
        ///        &quot;label&quot;: &quot;Филиал ФКУ «ЦВКГ им. П.В. Мандрыка» МО РФ клиника (преморб [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string InstitutionsLocation {
            get {
                return ResourceManager.GetString("InstitutionsLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [
        ///    {
        ///        &quot;grp&quot;: &quot;-&quot;,
        ///        &quot;label&quot;: &quot;-&quot;,
        ///        &quot;id&quot;: &quot;9e8429eb-9b03-463f-877c-09d8776b816d&quot;
        ///    },
        ///    {
        ///        &quot;grp&quot;: &quot;Солдаты, матросы, сержанты, старшины&quot;,
        ///        &quot;label&quot;: &quot;Рядовой&quot;,
        ///        &quot;id&quot;: &quot;7e8244d4-1c7c-4c05-bea0-8eaeffc54294&quot;
        ///    },
        ///    {
        ///        &quot;grp&quot;: &quot;Солдаты, матросы, сержанты, старшины&quot;,
        ///        &quot;label&quot;: &quot;Матрос&quot;,
        ///        &quot;id&quot;: &quot;d2354cd1-20e1-4d75-80d2-54a00f0f296d&quot;
        ///    },
        ///    {
        ///        &quot;grp&quot;: &quot;Солдаты, матросы, сержанты, старшины&quot;,
        ///        &quot;label&quot;: &quot;Ефрейтор [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string MilitaryRank {
            get {
                return ResourceManager.GetString("MilitaryRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [
        ///    {
        ///        &quot;label&quot;: &quot;-&quot;,
        ///        &quot;id&quot;: &quot;bf8fd633-d745-42a5-a524-76bb8afaec63&quot;
        ///    },
        ///    {
        ///        &quot;label&quot;: &quot;01069&quot;,
        ///        &quot;id&quot;: &quot;5bab98b0-3588-47dc-8b70-e0e9e3ed79ca&quot;
        ///    }
        ///].
        /// </summary>
        internal static string MilitaryUnit {
            get {
                return ResourceManager.GetString("MilitaryUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [
        ///    {
        ///        &quot;grp&quot;: &quot;-&quot;,
        ///        &quot;label&quot;: &quot;-&quot;,
        ///        &quot;id&quot;: &quot;ebac83b1-bdab-4d8f-aca2-42810002c520&quot;
        ///    },
        ///    {
        ///        &quot;grp&quot;: &quot;Акушерство и гинекология&quot;,
        ///        &quot;label&quot;: &quot;Акушер-гинеколог&quot;,
        ///        &quot;id&quot;: &quot;7aa012df-acab-414b-846f-05350d116e56&quot;
        ///    },
        ///    {
        ///        &quot;grp&quot;: &quot;Акушерство и гинекология&quot;,
        ///        &quot;label&quot;: &quot;Гинеколог&quot;,
        ///        &quot;id&quot;: &quot;8edf71c2-c99b-42ed-bd75-1ee1290673d2&quot;
        ///    },
        ///    {
        ///        &quot;grp&quot;: &quot;Акушерство и гинекология&quot;,
        ///        &quot;label&quot;: &quot;Хирург-гинеколог&quot;,
        ///        &quot;id&quot; [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Specialist {
            get {
                return ResourceManager.GetString("Specialist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [
        ///    {
        ///        &quot;label&quot;: &quot;-&quot;,
        ///        &quot;id&quot;: &quot;ffe83160-acce-434e-a04a-8cb9a37aca6c&quot;
        ///    },
        ///    {
        ///        &quot;label&quot;: &quot;Консультация&quot;,
        ///        &quot;id&quot;: &quot;a4808c06-ca79-4ae0-bc41-2a2eab25e3e9&quot;
        ///    },
        ///    {
        ///        &quot;label&quot;: &quot;Госпитализация&quot;,
        ///        &quot;id&quot;: &quot;1548f2c3-dc75-4d0d-a427-e62d2c4e7328&quot;
        ///    },
        ///    {
        ///        &quot;label&quot;: &quot;ВВК&quot;,
        ///        &quot;id&quot;: &quot;1de3524c-c537-49e3-8d6c-2f202b0321da&quot;
        ///    }
        ///].
        /// </summary>
        internal static string TypeOfDirection {
            get {
                return ResourceManager.GetString("TypeOfDirection", resourceCulture);
            }
        }
    }
}
